### ISSUE TITLE
Add support for electives - "pick one of these"

### ISSUE THREAD

**Issue by zhantongz** [ahoskins/Winston#20]
Say I need an arts options for one semester and I am interested in ECON 101, LING 101 and ANTHRO 101 but I can only take one because I have to take CHEM 211, 241, 263 and PHYS 144. It may be helpful for some to allow labelling some courses as possible options that can be neglected when making schedules if conflicting with a non-option course. For the above case, I would label ECON 101, LING 101, and ANTHRO 101 as options (and maybe rank them in preference) so if there is no schedule possible for ECON 101 with other "mandatory" courses, the schedule could be made with LING 101 or ANTHRO 101.

**Comment by rosshamish** [comment]
Hi! This is a great idea, and is something we're definitely looking to implement. The backend ([classtime](https://github.com/rosshamish/classtime)) supports this feature, so its a matter of sending the courses as electives to classtime during the schedule request. Docs on electives are here: http://classtime.readthedocs.org/en/latest/the-api.html#api-v1-generate-schedules

The gist is that we include a list of electives in the request, and classtime will include ONE course from the list in each schedule.

It's worth noting that multiple lists of electives are supported, so we should consider that when writing this feature (eg pick 1 from [ECON 101, LING 101] **and** pick 1 from [ANTHRO 101, PSYCH 104]).

Winston will need:
- in the UI, a way to bucket courses into (an) "electives" list(s)
- in the controllers, a way to store the courses in separate "electives" buckets
- in the schedule request, to attach the electives objects to the request

**Comment by ahoskins** [comment]
very related: #29
