### ISSUE TITLE
Schedule view should display the course title in the popover

### ISSUE THREAD

**Issue by tpavlek** [ahoskins/Winston#21]
If you're in schedule view and you have Math 114, Math 115 and Math 209 it is very difficult to tell what course is actually what if you don't have intimate knowledge of the course naming. If the popover had the course title followed by the description this would be much more clear and intuitive.

**Comment by rosshamish** [comment]
This makes a lot of sense. The implementation might even be easy. @ahoskins does the FullCalendar event have the course object's `title` as well as its `description`? 
https://github.com/ahoskins/Winston/blob/8edda7ff58c5f6b741b7e6b861cd629272cc2f01/public/js/controllers/scheduleCtrl.js#L85

**Comment by ahoskins** [comment]
Right now, the title property of each event is a shortened course name (MATH 114, MATH 115), and this is what shows up on the schedule itself.  The full course title (MATH 114: Introduction of Calculus I) is not currently in that object, but I think it's worth adding this.

Thanks for the suggestions @tpavlek!

**Comment by ahoskins** [comment]
closed in 7041525b83750706
