### ISSUE TITLE
Drag courses into the Added tray

### ISSUE THREAD

**Issue by rosshamish** [ahoskins/Winston#22]

**Comment by rosshamish** [comment]
I'm still a fan of this, even if only on desktop

**Comment by ahoskins** [comment]
Right now you in the half-done electives feature branch, there's a new added bar where drag and drop is fully in use.  Should be able to add expand the drag-and-drop to also affect the accordion.

**Comment by rosshamish** [comment]
Haha I know. "Wait, what was my plan here?" "This part is weird, what was I doing?"
