### ISSUE TITLE
Not creating valid schedule

### ISSUE THREAD

**Issue by shahzebasif** [ahoskins/Winston#24]
It won't work with my schedule for Fall 2015. I'm not sure if I'm using it right though.

Classes:
- ECE 304
- ECE 322
- ECE 410
- CMPUT 391

And you can add in ECE 440 if you like, it should fit.

I just get a "No schedules available! Modify your chosen classes or remove some busy time." prompt.

Here's my actual schedule in schedule builder:
![schedule_fall_2015](https://cloud.githubusercontent.com/assets/5952112/6815962/6a8fc256-d252-11e4-97b7-fd2eb2597885.png)

**Comment by rosshamish** [comment]
Ahh, that's probably ECE 304 being a nuisance. We're looking into that in rosshamish/classtime#98, "Specific courses/combinations with known scheduling issues". There's a couple other problem courses as well.

**Comment by rosshamish** [comment]
Just reproduced your issue. It's definitely ECE 304 being a nuisance. Try removing it from the list - you'll get schedules again.

**Comment by shahzebasif** [comment]
Just tried it. Yup, it works without ECE 304 and gives a great schedule too. So I'm just going to close this.
