### ISSUE TITLE
Wrapping schedule selector 

### ISSUE THREAD

**Issue by kyleoshaughnessy** [ahoskins/Winston#27]
Have the left and right arrows wrap around to the last and first items when viewing schedules. ie) 6 of 6 <-> 1 of 6

![](https://cloud.githubusercontent.com/assets/5834110/6860871/a42532e2-d3f3-11e4-9f35-87068cda3028.png)

**Comment by ahoskins** [comment]
Man, I listen to you! Only two hours later and this is resolved. closed ina9ad0c67

Check it out at http://thewinston-dev.herokuapp.com (the dev version of the site)

**Comment by kyleoshaughnessy** [comment]
Awesome!
