### ISSUE TITLE
Decouple localstorage from the all the rest

### ISSUE THREAD

**Issue by ahoskins** [ahoskins/Winston#30]
We both know that localstorage can really fuck with you sometime and makes many parts of the app less readable, less stable, and harder to debug.

Ideally it should be decoupled to the point where:
- we can turn it off easily while developing (by not injecting the localstorage service or whatever)
- all localstorage type code is contained in the singletons that hold the data (addedCourses service, etc) and of course some kind of localstorage service

This is something either of us can do at some time if we feel inspiration to do some useful refactoring.

**Comment by ahoskins** [comment]
I write this issue right now because I'm having the hardest time switching over addedCourses to support electives.  This'll probably be something I do first before doing any further non-UI stuff for electives.

**Comment by rosshamish** [comment]
Yeah I 100% agree here. We really rushed localStorage support out the door for the launch, it's really shaky.

**Comment by rosshamish** [comment]
We could refactor terms at the same time. At the very least we could replace all the `courses[currentTerm.term] && courses[currentTerm.term][course]` type things with a method that does the error check internally.

**Comment by rosshamish** [comment]
What's the status on this? I remember hearing something about progress on this

**Comment by ahoskins** [comment]
I believe this is done.  I know that as part of the electives I made some really tidy refactors to all things localstorage.  When I commit the localstorage stuff I'll close this
