### ISSUE TITLE
Foster student involvement

### ISSUE THREAD

**Issue by ahoskins** [ahoskins/Winston#34]
Can be broken down into a few categories:

**Developers:**
- Python experience OR
- Javascript/SPA experience OR

**Designers:**

**Marketing/Business:**

**Comment by rosshamish** [comment]
I think a good way to do this is to either chat with devs / comp sci students / comp eng students that we already know, *or* to meet some first/second year cs/compeng students.

Probably also useful to 1) identify bugs/enhancements/maintenace-tasks/docs-improvements, 2) create issues for them, 3) label them as first-contribution-friendly, 4) make it clear that the issue comments should be used to ask lots of questions about the code/docs/project.
