### ISSUE TITLE
investigate the benefits of using immutable data (for performance)

### ISSUE THREAD

**Issue by ahoskins** [ahoskins/Winston#35]
Immutable data can drastically [increase performance](https://www.youtube.com/watch?v=SiFwRtCnxv4).  It guarantees the validity of referential equality for a number of tasks like: memoization (which we do on search), stuff like `$scope.$watchCollection` (which we also do), and in React world it can do wonders when using [PureRenderMixin](https://facebook.github.io/react/docs/pure-render-mixin.html) (but since Angular renders straight into the DOM, *I don't think* this applies).

[ImmutibleJS](https://facebook.github.io/immutable-js/) is a popular Facebook project implementing all the normal data structures with persistent data structures.

**Comment by rosshamish** [comment]
This sounds like a good idea to me

**Comment by ahoskins** [comment]
relevent blog post: http://blog.mgechev.com/2015/03/02/immutability-in-angularjs-immutablejs/

**Comment by ahoskins** [comment]
Lol, no this is not happening anymore.  It performs good enough
